package com.raghib.polymorphism;

public class MethodOverriding {
	
	/**
	 * FOR OVERRING TRY TO GIVE EXAMPLE SPECIFIC TO YOUR APPLICATION FUNCTIONALITY.
	 * 
	 * EXAMPLE;
	 * 1> IN MY CASE I AM OVERRIDING THE BASE CLASS GETDRIVER METHOD IN ONE OF MY TEST CLASS
	 * TO LAUNCH BROWSER IN DIFFERENT SESSION. 
	 */
}
