package com.raghib.polymorphism;

public class MethodOverloading {
	/**
	 * CREATE REUSABLE CLASSES SUCH AS WAIT CLASS AND FRAME CLASS AND WROTE OVERLOADED METHODS IN THEM
	 * TO USE THEM IN TEST CLASSES AS PER THE REQUIREMENT.
	 * 
	 * EXAMPLE;
	 * 1> OVERLOADED EXPLICIT WAIT METHOD BASED ON USING WEBELEMENT AND XPATH.
	 * 
	 * 2> AS MY APPLICATION WAS HAVING LOT OF FRAMES SO CREATED OVERLOADED METHODS, 
	 * TO SELECT FRAME BASED ON ID, NAME AND WEBELEMENT, SO THAT I DON'T HAVE TO USE 
	 * DRIVER.SWITCHTO.FRAME[ID, NAME, WEBELEMENT] EVERYTIME.
	 */
}
