package com.raghib.encapsulation;

public class Encapsulation {
	
	/**
	 * HERE IF WE TAKE EXAMPLE OF POM FRAMEWORK EVERY TEST CLASS,
	 * PAGE CLASS AND OTHER CLASSES ARE AN EXAMPLE OF ENCAPSULATION.
	 * WHERE ALL ITEMS[LOCATORS, METHODS ETC.] SPECIFIC TO APPLICATION PAGE ARE
	 * ENCAPSULATED IN SINGLE UNIT OR PAGE CLASS.
	 */

}
