package com.raghib.inheritance;

public class Inheritance {
	
	/**
	 * AS WE KNOW INHERITANCE IS TO REUSE PARENT CLASS PROPERTIES IN CHILD CLASS.
	 * 
	 * EXAMPLE;
	 * HandleFrame.java
	 * 
	 * HERE WE CAN EXPLAIN HOW DRIVER CLASS OR BASE CLASS EXTENDED IN OTHER CLASSES
	 * TO UTILIZE THE BASE CLASS PROPERTIES IN CHILD CLASS.
	 * 
	 */

}
